In [44]:
# Import package
import numpy as np

In [45]:
# Activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of activation function
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

In [46]:
# Loss function
def mse_loss(y_true, y_predicted):
    return np.mean(np.square(y_true - y_predicted))

# Derivative of loss function
def mse_loss_derivative(y_true, y_predicted):
    return 2 * (y_predicted - y_true) / y_true.size

In [47]:
# Input data
X = np.array([[0.5, 0.2]])
# True outcome
y_true = np.array([[0.7]])

# Initial parameters of the hidden layer
W_h = np.array([[0.05, 0.1],
                [0.02, 0.08]])
b_h = np.array([[0.01, 0.02]])

# Initial parameters of the output layer
W_o = np.array([[0.1],
                [0.03]])
b_o = np.array([[0.05]])

### Step 1: forward pass

In [48]:
# np.dot() here performs matrix multiplication since X and W_h are both 2-D arrays.
Z_h = np.dot(X, W_h) + b_h
A_h = sigmoid(Z_h)

Z_o = np.dot(A_h, W_o) + b_o
A_o = sigmoid(Z_o)

### Step 2: calculate errors

In [49]:
loss = mse_loss(y_true, A_o)
print("Loss:", loss)

Loss: 0.029199334546921443


### Step 3: backward pass

In [50]:
dLoss_dA_o = mse_loss_derivative(y_true, A_o)
dA_o_dZ_o = sigmoid_derivative(Z_o)
delta_o = dLoss_dA_o * dA_o_dZ_o

grad_W_o = np.dot(A_h.T, delta_o)
grad_b_o = np.sum(delta_o, axis=0, keepdims=True)

dLoss_dA_h = np.dot(delta_o, W_o.T)
dA_h_dZ_h = sigmoid_derivative(Z_h)
delta_h = dLoss_dA_h * dA_h_dZ_h

grad_W_h = np.dot(X.T, delta_h)
grad_b_h = np.sum(delta_h, axis=0, keepdims=True)

### Step 4: update parameters

In [51]:
learning_rate = 0.2

W_o -= learning_rate * grad_W_o
b_o -= learning_rate * grad_b_o
W_h -= learning_rate * grad_W_h
b_h -= learning_rate * grad_b_h

# Print updated parameters
print("Updated W_o:\n", W_o)
print("Updated b_o:\n", b_o)
print("Updated W_h:\n", W_h)
print("Updated b_h:\n", b_h)

Updated W_o:
 [[0.10868094]
 [0.03888084]]
Updated b_o:
 [[0.06702985]]
Updated W_h:
 [[0.05021279 0.10006374]
 [0.02008512 0.0800255 ]]
Updated b_h:
 [[0.01042558 0.02012749]]


In [52]:
epochs=200

for i in range(0,epochs+1):
    Z_h = np.dot(X, W_h) + b_h
    A_h = sigmoid(Z_h)

    Z_o = np.dot(A_h, W_o) + b_o
    A_o = sigmoid(Z_o)
    
    loss = mse_loss(y_true, A_o)
    
    dLoss_dA_o = mse_loss_derivative(y_true, A_o)
    dA_o_dZ_o = sigmoid_derivative(Z_o)
    delta_o = dLoss_dA_o * dA_o_dZ_o

    grad_W_o = np.dot(A_h.T, delta_o)
    grad_b_o = np.sum(delta_o, axis=0, keepdims=True)

    dLoss_dA_h = np.dot(delta_o, W_o.T)
    dA_h_dZ_h = sigmoid_derivative(Z_h)
    delta_h = dLoss_dA_h * dA_h_dZ_h

    grad_W_h = np.dot(X.T, delta_h)
    grad_b_h = np.sum(delta_h, axis=0, keepdims=True)
    
    W_o -= learning_rate * grad_W_o
    b_o -= learning_rate * grad_b_o
    W_h -= learning_rate * grad_W_h
    b_h -= learning_rate * grad_b_h
    
    if i%20==0:
        print(f"Iteration = {i}")
        print("Loss:", loss)
        print("Updated W_o:\n", W_o)
        print("Updated b_o:\n", b_o)
        print("Updated W_h:\n", W_h)
        print("Updated b_h:\n", b_h)
        print("\n--------------------------------------")
    

Iteration = 0
Loss: 0.02702075180819914
Updated W_o:
 [[0.11701991]
 [0.0474102 ]]
Updated b_o:
 [[0.08338441]]
Updated W_h:
 [[0.05043488 0.10014308]
 [0.02017395 0.08005723]]
Updated b_h:
 [[0.01086977 0.02028616]]

--------------------------------------
Iteration = 20
Loss: 0.006192430647100046
Updated W_o:
 [[0.229655  ]
 [0.16246166]]
Updated b_o:
 [[0.30367825]]
Updated W_h:
 [[0.05512248 0.10294282]
 [0.02204899 0.08117713]]
Updated b_h:
 [[0.02024496 0.02588564]]

--------------------------------------
Iteration = 40
Loss: 0.001642193958078419
Updated W_o:
 [[0.28283939]
 [0.21668733]]
Updated b_o:
 [[0.40714574]]
Updated W_h:
 [[0.05841588 0.10537057]
 [0.02336635 0.08214823]]
Updated b_h:
 [[0.02683176 0.03074113]]

--------------------------------------
Iteration = 60
Loss: 0.00047757605212629624
Updated W_o:
 [[0.30994208]
 [0.24429638]]
Updated b_o:
 [[0.45969508]]
Updated W_h:
 [[0.0603562  0.10687598]
 [0.02414248 0.08275039]]
Updated b_h:
 [[0.0307124  0.03375195]]

---